version: '3.7'
services:
  web:
    image: nginx:latest
    volumes:
      - ./client/build:/usr/share/nginx/html
    ports:
      - "3000:80"
  node:
    build:
      context: ./server
    volumes:
      - ./server:/home/node/app
    ports:
      - "4000:4000"

